# Generated by Django 2.2.20 on 2021-09-23 11:33

from django.db import migrations

NEW_BUILDING_YEAR = 2015

def set_new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Flat.objects.filter(construction_year__gte=NEW_BUILDING_YEAR).update(new_building=True)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(set_new_building),
    ]